#pragma once
// Generated by scripts/generate_ui_strings.py — do not edit by hand.

namespace UiStrings {
    inline constexpr const char StartGame[] = u8"\xe9\x96\x8b\xe5\xa7\x8b\xe9\x81\x8a\xe6\x88\xb2";
    inline constexpr const char QuitGame[] = u8"\xe9\x9b\xa2\xe9\x96\x8b\xe9\x81\x8a\xe6\x88\xb2";
    inline constexpr const char TitleMain[] = u8"\xe5\x8d\xa1\xe9\x80\x9a\xe7\x82\xb8\xe5\xbd\x88\xe4\xba\xba";
    inline constexpr const char Subtitle[] = u8"\xe7\x88\x86\xe7\x88\x86\xe7\x8e\x8b\xe9\xa2\xa8\xe6\xa0\xbc\x20\xc2\xb7\x20\xe6\x9c\x9f\xe6\x9c\xab\xe5\xb0\x88\xe9\xa1\x8c\xe9\x97\x96\xe9\x97\x9c";
    inline constexpr const char PickDifficulty[] = u8"\xe9\x81\xb8\xe6\x93\x87\xe9\x9b\xa3\xe5\xba\xa6";
    inline constexpr const char PickMode[] = u8"\xe9\x81\x8a\xe6\x88\xb2\xe6\xa8\xa1\xe5\xbc\x8f";
    inline constexpr const char Easy[] = u8"\xe7\xb0\xa1\xe5\x96\xae";
    inline constexpr const char Normal[] = u8"\xe6\x99\xae\xe9\x80\x9a";
    inline constexpr const char Hard[] = u8"\xe5\x9b\xb0\xe9\x9b\xa3";
    inline constexpr const char EasyDesc[] = u8"\x31\x20\xe9\x9a\xbb\xe6\x95\xb5\xe4\xba\xba\x20\xc2\xb7\x20\xe5\xb0\x91\xe6\x94\xbe\xe7\x82\xb8\xe5\xbd\x88";
    inline constexpr const char NormalDesc[] = u8"\x32\x20\xe9\x9a\xbb\xe6\x95\xb5\xe4\xba\xba\x20\xc2\xb7\x20\xe6\x9c\x83\xe7\x82\xb8\xe7\x89\x86";
    inline constexpr const char HardDesc[] = u8"\x33\x20\xe9\x9a\xbb\xe6\x95\xb5\xe4\xba\xba\x20\xc2\xb7\x20\xe7\xa9\x8d\xe6\xa5\xb5\xe8\xbf\xbd\xe6\x93\x8a";
    inline constexpr const char ControlsTitle[] = u8"\xe6\x93\x8d\xe4\xbd\x9c\xe8\xaa\xaa\xe6\x98\x8e\xef\xbc\x88\xe5\xa4\xa7\xe5\xad\x97\xe7\x89\x88\xef\xbc\x89";
    inline constexpr const char ControlsLine1[] = u8"\xe7\xa7\xbb\xe5\x8b\x95\xef\xbc\x9a\xe6\x96\xb9\xe5\x90\x91\xe9\x8d\xb5\x20\xe6\x88\x96\x20\x57\x41\x53\x44";
    inline constexpr const char ControlsLine2[] = u8"\xe6\x94\xbe\xe5\xbd\x88\xef\xbc\x9a\xe7\xa9\xba\xe7\x99\xbd\xe9\x8d\xb5\x20\x20\x20\x20\xe9\x87\x8d\xe9\x96\x8b\xef\xbc\x9a\x52\x20\x20\x20\x20\xe5\x9b\x9e\xe9\x81\xb8\xe5\x96\xae\xef\xbc\x9a\x45\x73\x63";
    inline constexpr const char ControlsLine3[] = u8"\xe9\x9b\x99\xe4\xba\xba\xef\xbc\x9a\x50\x31\x20\x57\x41\x53\x44\x2b\xe7\xa9\xba\xe7\x99\xbd\x20\x20\x50\x32\x20\xe6\x96\xb9\xe5\x90\x91\xe9\x8d\xb5\x2b\x45\x6e\x74\x65\x72\x20\x20\xe9\x80\xa3\xe7\xb7\x9a\xef\xbc\x9a\xe5\x85\x88\xe9\x96\x8b\xe6\x88\xbf\xe5\x86\x8d\xe5\x8a\xa0\xe5\x85\xa5";
    inline constexpr const char ModeSolo[] = u8"\xe5\x96\xae\xe4\xba\xba";
    inline constexpr const char ModeDuo[] = u8"\xe9\x9b\x99\xe4\xba\xba";
    inline constexpr const char ModeHost[] = u8"\xe9\x96\x8b\xe6\x88\xbf";
    inline constexpr const char ModeJoin[] = u8"\xe5\x8a\xa0\xe5\x85\xa5";
    inline constexpr const char FontDown[] = u8"\xe5\xad\x97\xe9\xab\x94\x2d";
    inline constexpr const char FontUp[] = u8"\xe5\xad\x97\xe9\xab\x94\x2b";
    inline constexpr const char HighScore[] = u8"\xe6\x9c\x80\xe9\xab\x98\xe5\x88\x86";
    inline constexpr const char Score[] = u8"\xe5\x88\x86\xe6\x95\xb8";
    inline constexpr const char EnemiesLeft[] = u8"\xe6\x95\xb5\xe4\xba\xba";
    inline constexpr const char Bomb[] = u8"\xe7\x82\xb8\xe5\xbd\x88";
    inline constexpr const char Fire[] = u8"\xe7\x81\xab\xe5\x8a\x9b";
    inline constexpr const char Goal[] = u8"\xe7\x9b\xae\xe6\xa8\x99\xef\xbc\x9a\xe6\xb6\x88\xe6\xbb\x85\xe6\x89\x80\xe6\x9c\x89\xe6\x95\xb5\xe4\xba\xba";
    inline constexpr const char HintPlaying[] = u8"\xe7\xa9\xba\xe7\x99\xbd\xe6\x94\xbe\xe5\xbd\x88\x20\xc2\xb7\x20\xe7\x82\xb8\xe7\x89\x86\xe5\x8f\xaf\xe8\x83\xbd\xe6\x8e\x89\xe9\x81\x93\xe5\x85\xb7\x20\xc2\xb7\x20\xe6\x95\xb5\xe5\xbd\x88\xe4\xb9\x9f\xe6\x9c\x83\xe7\x82\xb8\xe7\x89\x86";
    inline constexpr const char HintGameOver[] = u8"\xe5\xa4\xb1\xe6\x95\x97\x20\xe2\x80\x94\x20\xe6\x8c\x89\x20\x52\x20\xe9\x87\x8d\xe8\xa9\xa6";
    inline constexpr const char HintVictory[] = u8"\xe9\x80\x9a\xe9\x97\x9c\x20\xe2\x80\x94\x20\xe6\x8c\x89\x20\x52\x20\xe5\x86\x8d\xe7\x8e\xa9";
    inline constexpr const char Win[] = u8"\xe9\x80\x9a\xe9\x97\x9c\xe5\x8b\x9d\xe5\x88\xa9\xef\xbc\x81";
    inline constexpr const char Lose[] = u8"\xe8\xa2\xab\xe6\x93\x8a\xe6\x95\x97\xe4\xba\x86";
    inline constexpr const char Restart[] = u8"\xe6\x8c\x89\x20\x52\x20\xe9\x87\x8d\xe9\x96\x8b\xe6\x9c\xac\xe5\xb1\x80";
    inline constexpr const char TitleFallback[] = u8"\xe5\x8d\xa1\xe9\x80\x9a\xe7\x82\xb8\xe5\xbd\x88\xe4\xba\xba";
    inline constexpr const char MainMenu[] = u8"\xe8\xbf\x94\xe5\x9b\x9e\xe4\xb8\xbb\xe9\x81\xb8\xe5\x96\xae";
    inline constexpr const char PickAction[] = u8"\xe8\xab\x8b\xe9\x81\xb8\xe6\x93\x87\xef\xbc\x9a";
    inline constexpr const char PlayAgain[] = u8"\xe5\x86\x8d\xe7\x8e\xa9\xe4\xb8\x80\xe5\xb1\x80";

    inline constexpr int kCodepoints[] = {
        0x0020,
        0x002B,
        0x002D,
        0x0030,
        0x0031,
        0x0032,
        0x0033,
        0x0034,
        0x0035,
        0x0036,
        0x0037,
        0x0038,
        0x0039,
        0x0041,
        0x0044,
        0x0045,
        0x0050,
        0x0052,
        0x0053,
        0x0057,
        0x0063,
        0x0065,
        0x006E,
        0x0072,
        0x0073,
        0x0074,
        0x0078,
        0x00B7,
        0x2014,
        0x4E00,
        0x4E3B,
        0x4E5F,
        0x4E86,
        0x4EBA,
        0x4F5C,
        0x5148,
        0x5165,
        0x5177,
        0x518D,
        0x5206,
        0x5229,
        0x529B,
        0x52A0,
        0x52D5,
        0x52DD,
        0x5361,
        0x53EF,
        0x5411,
        0x55AE,
        0x56DE,
        0x56F0,
        0x5927,
        0x5931,
        0x59CB,
        0x5B57,
        0x5C08,
        0x5C11,
        0x5C40,
        0x5EA6,
        0x5F0F,
        0x5F48,
        0x6216,
        0x6232,
        0x623F,
        0x6240,
        0x6309,
        0x6389,
        0x64C7,
        0x64CA,
        0x64CD,
        0x653E,
        0x6557,
        0x6575,
        0x6578,
        0x65B9,
        0x660E,
        0x666E,
        0x6700,
        0x6703,
        0x6709,
        0x671F,
        0x672B,
        0x672C,
        0x683C,
        0x6975,
        0x6A19,
        0x6A21,
        0x6D88,
        0x6EC5,
        0x706B,
        0x70B8,
        0x7206,
        0x7246,
        0x7248,
        0x738B,
        0x73A9,
        0x767D,
        0x76EE,
        0x79FB,
        0x7A4D,
        0x7A7A,
        0x7C21,
        0x7DDA,
        0x80FD,
        0x88AB,
        0x8A66,
        0x8AAA,
        0x8ACB,
        0x8FD4,
        0x8FFD,
        0x901A,
        0x9023,
        0x904A,
        0x9053,
        0x9078,
        0x91CD,
        0x9375,
        0x958B,
        0x95D6,
        0x95DC,
        0x96BB,
        0x96D9,
        0x96E2,
        0x96E3,
        0x984C,
        0x98A8,
        0x9AD4,
        0x9AD8,
        0xFF01,
        0xFF08,
        0xFF09,
        0xFF1A
    };
    inline constexpr int kCodepointCount =
        static_cast<int>(sizeof(kCodepoints) / sizeof(kCodepoints[0]));
}  // namespace UiStrings
