#!/usr/bin/env python3
"""Emit UiStrings.hpp with UTF-8 \\x escapes (MSVC/g++ encoding safe)."""
from pathlib import Path

STRINGS = {
    "StartGame": "開始遊戲",
    "QuitGame": "離開遊戲",
    "TitleMain": "卡通炸彈人",
    "Subtitle": "爆爆王風格 · 期末專題闖關",
    "PickDifficulty": "選擇難度",
    "PickMode": "遊戲模式",
    "Easy": "簡單",
    "Normal": "普通",
    "Hard": "困難",
    "EasyDesc": "1 隻敵人 · 少放炸彈",
    "NormalDesc": "2 隻敵人 · 會炸牆",
    "HardDesc": "3 隻敵人 · 積極追擊",
    "ControlsTitle": "操作說明（大字版）",
    "ControlsLine1": "移動：方向鍵 或 WASD",
    "ControlsLine2": "放彈：空白鍵    重開：R    回選單：Esc",
    "ControlsLine3": "雙人：P1 WASD+空白  P2 方向鍵+Enter  連線：先開房再加入",
    "ModeSolo": "單人",
    "ModeDuo": "雙人",
    "ModeHost": "開房",
    "ModeJoin": "加入",
    "FontDown": "字體-",
    "FontUp": "字體+",
    "HighScore": "最高分",
    "Score": "分數",
    "EnemiesLeft": "敵人",
    "Bomb": "炸彈",
    "Fire": "火力",
    "Goal": "目標：消滅所有敵人",
    "HintPlaying": "空白放彈 · 炸牆可能掉道具 · 敵彈也會炸牆",
    "HintGameOver": "失敗 — 按 R 重試",
    "HintVictory": "通關 — 按 R 再玩",
    "Win": "通關勝利！",
    "Lose": "被擊敗了",
    "Restart": "按 R 重開本局",
    "TitleFallback": "卡通炸彈人",
    "MainMenu": "返回主選單",
    "PickAction": "請選擇：",
    "PlayAgain": "再玩一局",
}

EXTRA_CHARS = "0123456789x·—返主單"


def to_c_utf8(name: str, text: str) -> str:
    esc = "".join(f"\\x{b:02x}" for b in text.encode("utf-8"))
    return f'inline constexpr const char {name}[] = u8"{esc}";'


def main() -> None:
    all_text = "".join(STRINGS.values()) + EXTRA_CHARS
    cps = sorted({ord(c) for c in all_text})
    cp_lines = ",\n        ".join(f"0x{cp:04X}" for cp in cps)

    lines = [
        "#pragma once",
        "// Generated by scripts/generate_ui_strings.py — do not edit by hand.",
        "",
        "namespace UiStrings {",
    ]
    for name, text in STRINGS.items():
        lines.append("    " + to_c_utf8(name, text))
    lines.append("")
    lines.append("    inline constexpr int kCodepoints[] = {")
    lines.append(f"        {cp_lines}")
    lines.append("    };")
    lines.append("    inline constexpr int kCodepointCount =")
    lines.append(f"        static_cast<int>(sizeof(kCodepoints) / sizeof(kCodepoints[0]));")
    lines.append("}  // namespace UiStrings")
    lines.append("")

    out = Path(__file__).resolve().parents[1] / "include" / "UiStrings.hpp"
    out.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", out, "codepoints", len(cps))


if __name__ == "__main__":
    main()
